name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["Turing-Complete-Game/1"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: discord
    attributes:
      label: Discord Thread
      description: "Please create/link a thread in the discord for this issue, and don't forget to also backlink from there to here."
      placeholder: ex. https://discord.com/channels/828292123936948244/...
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running? (see main menu)
      placeholder: 0.1066 Beta
    validations:
      required: true
  - type: dropdown
    id: OS
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - MacOS
        - Linux
  - type: textarea
    id: logs
    attributes:
      label: Relevant `debug.log` output, search next to the exectuable
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
