name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - Stuffe
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |Also tell us, what did you expect to happen? Please be as clear as possible. If I can recreate the issue on my computer, you will likely see the patch very soon.
                    You can upload your save as a .zip by dragging and dropping to the textbox below
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of the game are you running?
      options:
        - Latest
        - Development
        - Other
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      description: What Operating System are you running on?
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Turing-Complete-Game/Suggestions-and-Issues/blob/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
