name: Feature Request
description: File a feature request
title: "[Request]: "
labels: ["enhancement"]
assignees:
  - Stuffe
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form!
  - type: textarea
    id: feature
    attributes:
      label: Request?
      description: What do you want to see added to Turing Complete!
      placeholder: Tell us what you want to see!
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Turing-Complete-Game/Suggestions-and-Issues/blob/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
